<?php
$GLOBALS['nids_dataset_fields'] = array(
  'overview' => array(
    'nichoirid',
    'userid',
    'typeobs',
    'obsval'
  ),
);

/**
 * Implements hook_node_info().
 */
function nids_node_info() {
  $info = array();

  $info['nids'] = array(
    'name'        => t('Observations nichoir'),
    'base'        => 'nids',
    'module'      => 'nids',
    'description' => t('Ajout observations nichoir.'),
    'has_body'    => FALSE
  );
  return $info;
}

function nids_init() {
  $module_path = base_path().drupal_get_path('module', 'nids');
  drupal_add_js(array(
    'nids_path' => $module_path,
    'nids_callback_base_url' => base_path().'nids'
    ), 'setting');
}

// Implementation of hook_menu(): used to create a page for the form
function nids_menu() {
  $items = array();
  return $items;
}


// Form builder. Form ID = function name
function nids_nichoir_form($form, &$form_state) {

    $form['nichoir'] = array(
      '#title' => t("Pour quel nichoir?"),
      '#type' => 'select',
      '#options' => array(
        'Choisir' => 'Choisir...',
        123 => 123,
        221 => 221,
        ),
      '#required' => TRUE,
      '#default_value' => 'Choisir',
    );

    $form['date'] = array(
      '#type' => 'date_popup',
      '#date_format' => 'Y-m-d H:i a',
      '#size' => 30,
      '#title' => "Date et heure de l'observation",
      '#states' => array(
        'visible' => array(
          ':input[name="nichoir"]' => array('!value' => 'Choisir'),
        ),
      ),
    );

    $form['espece'] = array(
      '#title' => t("Quelle espèce?"),
      '#type' => 'select',
      '#options' => array(
        'Choisir' => 'Choisir...',
        'Moineau_domestique' => 'Moineau domestique',
        'Hirondelle_bicolore' => 'Hirondelle bicolore',
        'Mesange_a_tete_noire' => 'Mésange à tête noire',
        'Mesange_brune' => 'Mésange brune',
        'Inconnue' => 'Inconnue',
        'Autre' => 'Autre'
        ),
      '#required' => TRUE,
      '#default_value' => 'Choisir',
      '#states' => array(
        'visible' => array(
          ':input[name="nichoir"]' => array('!value' => 'Choisir'),
        ),
      ),
    );


    $form['espece_autre'] = array(
      '#type' => 'textfield',
      '#size' => 70,
      '#title' => '<h4>'.t("Veuillez préciser l'espèce...").'</h4>',
      '#states' => array(
        'visible' => array(
          ':input[name="espece"]' => array('value' => 'Autre'),
          ':input[name="nichoir"]' => array('!value' => 'Choisir'),
        ),
      ),
    );

    $form['type_obs'] = array(
      '#title' => t("Type d'observation"),
      '#type' => 'radios',
      '#size' => 50,
      '#required' => FALSE,
      '#options' => array(
        1 => t('Entrée ou sortie du nichoir pour la première fois'),
        2 => t('Apport de brindilles'),
        3 => t("Activités menant à la conception éventuelle d'un bébé"),
        4 => t('Sons de poussins, quémande alimentaire'),
        5 => t('Alimentation des poussins par les parents (bec avec des chenilles, etc.)'),
        6 => t('Parent en attente près du nichoir'),
        7 => t('Oiseau chante sur nichoir'),
        8 => t('Les oiseaux ne visitent plus le nichoir'),
        9 => t('Indiquer un nombre de visites au nichoir pendant 5 minutes'),
        10 => t('Autre'),
        ),
      '#states' => array(
        'visible' => array(
          ':input[name="espece"]' => array('!value' => 'Choisir'),
        ),
      ),

       );

    $form['type_obs_autre'] = array(
      '#type' => 'textfield',
      '#size' => 70,
      '#title' => '<h4>'.t("Veuillez préciser...").'</h4>',
      '#states' => array(
        'visible' => array(
          ':input[name="type_obs"]' => array('value' => 10),
          ':input[name="espece"]' => array('!value' => 'Choisir'),
        ),
      ),
    );

    $form['nombre_visite'] = array(
      '#type' => 'textfield',
      '#size' => 70,
      '#title' => '<h4>'.t("Indiquer le nombre de visites au nichoir enregistrées pendant une période de 5 minutes...").'</h4>',
      '#states' => array(
        'visible' => array(
          ':input[name="type_obs"]' => array('value' => 9),
          ':input[name="espece"]' => array('!value' => 'Choisir'),
        ),
      ),
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t("Ajouter l'observation!"),
      '#states' => array(
        'visible' => array(
          ':input[name="type_obs"]' => array('!value' => false),
          ':input[name="espece"]' => array('!value' => 'Choisir'),
        ),
      ),
    );

    $module_path = base_path().drupal_get_path('module', 'nids');
    $js_files = array(
      'http://maps.google.com/maps/api/js?sensor=false',
      $module_path . '/javascript/nids.map.js',
      $module_path . '/javascript/nids.taxonomy.js',
      );
    $form['#attached']['js'] = $js_files;
    $form['#validate'][] = 'nids_form_validate';
    $form['#submit'][] = 'nids_form_submit';
    return $form;
}


// Form validation handler.
function nids_form_validate($form, &$form_state) {
  //do validation here if necessary
}


// Form submit handler.
function nids_form_submit($form, &$form_state) {
 }


function nids_insert($node) {
}

function nids_update($node) {
}

function nids_delete($node) {
}

function nids_load($nodes) {
}

function _nids_fields($node) {
}



/**
 * Implements hook_block_info().
 */
function nids_block_info() {
  $blocks = array();
  $blocks['form_nichoir'] = array(
    'info' => t('A block to show the form for nichoirs'),
    'cache' => DRUPAL_NO_CACHE,
    'region' => 'content',
    'status' => TRUE,
    'visibility' => BLOCK_VISIBILITY_PHP,
    'pages' => '<?php 
      if(arg(0) == "node" && is_numeric(arg(1))){
        $nid = arg(1);
        $nnode = node_load($nid);
        if ($nnode->type == "nids"){
          return TRUE;
        }
      }
      return FALSE; ?>'
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function nids_block_view($block_name = '') {
  if ($block_name == 'form_nichoir') {
    $form=drupal_get_form('nids_nichoir_form');
    $content=$form;
    //Return the content of the block
    //$content=theme('table', array('header' => $header, 'rows' => $rows));
    $block = array(
      'subject' => '',
      'content' => $content,
    );
    return $block;
  }
}



?>
